# Generated by Django 4.0.1 on 2022-01-31 12:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField(validators=[django.core.validators.MinValueValidator])),
            ],
        ),
    ]
