# Generated by Django 4.0.1 on 2022-01-31 14:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subtotal_price', models.IntegerField(default=0)),
                ('shipping_price', models.IntegerField(default=0)),
                ('tax_price', models.IntegerField(default=0)),
                ('total_price', models.IntegerField(default=0)),
                ('items_amount', models.IntegerField(default=0)),
                ('products', models.ManyToManyField(to='products.Product')),
            ],
        ),
    ]
