# Generated by Django 4.0.1 on 2022-02-04 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_cart_session_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='session',
        ),
    ]
